CC=g++
FLAGS=-std=c++17 -pedantic -Wall -Wextra -Wno-unused-variable

lab1: 
	$(CC) $(FLAGS) lab1.cpp -o lab1.out
lab2_treap:
	$(CC) $(FLAGS) lab2_treap.cpp -o lab2_treap.out
lab2_avl:
	$(CC) $(FLAGS) lab2_avl.cpp -o lab2_avl.out
clean:
	rm *.out